# -*- coding: utf-8 -*-
"""Event class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQEdy9oTIaAlPRWbBM3dfOoeHIbKxiUZ
"""

class Event:
    def __init__(self, event_id, type, theme, date, time, duration, venue, client, guest_list, catering_company,
                 cleaning_company, decorations_company, entertainment_company, furniture_company, invoice):
        self._event_id = event_id
        self._type = type
        self._theme = theme
        self._date = date
        self._time = time
        self._duration = duration
        self._venue = venue
        self._client = client
        self._guest_list = guest_list
        self._catering_company = catering_company
        self._cleaning_company = cleaning_company
        self._decorations_company = decorations_company
        self._entertainment_company = entertainment_company
        self._furniture_company = furniture_company
        self._invoice = invoice

    # Getter and Setter methods
    def get_event_id(self):
        return self._event_id

    def set_event_id(self, event_id):
        self._event_id = event_id

    def get_type(self):
        return self._type

    def set_type(self, type):
        self._type = type

    def get_theme(self):
        return self._theme

    def set_theme(self, theme):
        self._theme = theme

    def get_date(self):
        return self._date

    def set_date(self, date):
        self._date = date

    def get_time(self):
        return self._time

    def set_time(self, time):
        self._time = time

    def get_duration(self):
        return self._duration

    def set_duration(self, duration):
        self._duration = duration

    def get_venue(self):
        return self._venue

    def set_venue(self, venue):
        self._venue = venue

    def get_client(self):
        return self._client

    def set_client(self, client):
        self._client = client

    def get_guest_list(self):
        return self._guest_list

    def add_guest(self, guest):
        self._guest_list.append(guest)

    def remove_guest(self, guest):
        self._guest_list.remove(guest)

    def get_catering_company(self):
        return self._catering_company

    def set_catering_company(self, catering_company):
        self._catering_company = catering_company

    def get_cleaning_company(self):
        return self._cleaning_company

    def set_cleaning_company(self, cleaning_company):
        self._cleaning_company = cleaning_company

    def get_decorations_company(self):
        return self._decorations_company

    def set_decorations_company(self, decorations_company):
        self._decorations_company = decorations_company

    def get_entertainment_company(self):
        return self._entertainment_company

    def set_entertainment_company(self, entertainment_company):
        self._entertainment_company = entertainment_company

    def get_furniture_company(self):
        return self._furniture_company

    def set_furniture_company(self, furniture_company):
        self._furniture_company = furniture_company

    def get_invoice(self):
        return self._invoice

    def set_invoice(self, invoice):
        self._invoice = invoice