# -*- coding: utf-8 -*-
"""Salesperson class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b2sWWAwJLeFbmU8Ds0DPCVxTaZvyjQIk
"""

class Salesperson(Employee):
    def __init__(self, name, employee_id, department, job_title, basic_salary, age, date_of_birth, passport_details):
        super().__init__(name, employee_id, department, job_title, basic_salary, age, date_of_birth, passport_details)
        self._manager = None

    def get_manager(self):
        return self._manager

    def set_manager(self, manager):
        self._manager = manager